// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface LendingAccountingLib$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "LendingAccountingLib";
  readonly sourceName: "contracts/libraries/LendingAccountingLib.sol";
  readonly abi: [];
  readonly bytecode: "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212203d4bc4f28e36c73c38794bc6987ec11c50844f13c6fe32098a2cbe5b9ff9e66664736f6c63430008130033";
  readonly deployedBytecode: "0x600080fdfea26469706673582212203d4bc4f28e36c73c38794bc6987ec11c50844f13c6fe32098a2cbe5b9ff9e66664736f6c63430008130033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/LendingAccountingLib.sol";
  readonly buildInfoId: "solc-0_8_19-148c98347c17a2f8ea0df427354d3cdb12644a10";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["LendingAccountingLib"]: LendingAccountingLib$Type;
    ["contracts/libraries/LendingAccountingLib.sol:LendingAccountingLib"]: LendingAccountingLib$Type;
  }
}