// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IComplianceHook$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IComplianceHook";
  readonly sourceName: "contracts/interfaces/IComplianceHook.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"nftId","type":"uint256"},{"internalType":"address","name":"borrower","type":"address"}],"name":"canOpenPosition","outputs":[{"internalType":"bool","name":"ok","type":"bool"},{"internalType":"bytes32","name":"reasonCode","type":"bytes32"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"nftId","type":"uint256"},{"internalType":"address","name":"account","type":"address"}],"name":"canRefreshProof","outputs":[{"internalType":"bool","name":"ok","type":"bool"},{"internalType":"bytes32","name":"reasonCode","type":"bytes32"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IComplianceHook.sol";
  readonly buildInfoId: "solc-0_8_19-1ef7364bee65fe47cce44adf0cd306f2b04bd606";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IComplianceHook"]: IComplianceHook$Type;
    ["contracts/interfaces/IComplianceHook.sol:IComplianceHook"]: IComplianceHook$Type;
  }
}