// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IEmergencyControls$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IEmergencyControls";
  readonly sourceName: "contracts/interfaces/IEmergencyControls.sol";
  readonly abi: [{"inputs":[],"name":"oracleUpdatesPaused","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"riskMode","outputs":[{"internalType":"enum IEmergencyControls.ProtocolRiskMode","name":"","type":"uint8"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IEmergencyControls.sol";
  readonly buildInfoId: "solc-0_8_19-1ef7364bee65fe47cce44adf0cd306f2b04bd606";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IEmergencyControls"]: IEmergencyControls$Type;
    ["contracts/interfaces/IEmergencyControls.sol:IEmergencyControls"]: IEmergencyControls$Type;
  }
}