// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface BNBChainIds$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "BNBChainIds";
  readonly sourceName: "contracts/bnb/BNBChainIds.sol";
  readonly abi: [];
  readonly bytecode: "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea264697066735822122064761e8fe1c9a54df56724eb96c0794b2f3fcca2416598eab3fff74b78ecd52e64736f6c63430008130033";
  readonly deployedBytecode: "0x600080fdfea264697066735822122064761e8fe1c9a54df56724eb96c0794b2f3fcca2416598eab3fff74b78ecd52e64736f6c63430008130033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/bnb/BNBChainIds.sol";
  readonly buildInfoId: "solc-0_8_19-1ef7364bee65fe47cce44adf0cd306f2b04bd606";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["BNBChainIds"]: BNBChainIds$Type;
    ["contracts/bnb/BNBChainIds.sol:BNBChainIds"]: BNBChainIds$Type;
  }
}