// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IOracle$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IOracle";
  readonly sourceName: "contracts/interfaces/IOracle.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"nftId","type":"uint256"}],"name":"getCollateralValue","outputs":[{"internalType":"uint256","name":"usdValue","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IOracle.sol";
  readonly buildInfoId: "solc-0_8_19-1ef7364bee65fe47cce44adf0cd306f2b04bd606";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IOracle"]: IOracle$Type;
    ["contracts/interfaces/IOracle.sol:IOracle"]: IOracle$Type;
  }
}