// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IFeeDiscountModule$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IFeeDiscountModule";
  readonly sourceName: "contracts/interfaces/IFeeDiscountModule.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"borrower","type":"address"}],"name":"originationDiscountBps","outputs":[{"internalType":"uint16","name":"","type":"uint16"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IFeeDiscountModule.sol";
  readonly buildInfoId: "solc-0_8_19-1ef7364bee65fe47cce44adf0cd306f2b04bd606";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IFeeDiscountModule"]: IFeeDiscountModule$Type;
    ["contracts/interfaces/IFeeDiscountModule.sol:IFeeDiscountModule"]: IFeeDiscountModule$Type;
  }
}