// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IYieldUpdateMirror$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IYieldUpdateMirror";
  readonly sourceName: "contracts/interfaces/IYieldUpdateMirror.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"nftId","type":"uint256"}],"name":"borrowSafetyBps","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"nftId","type":"uint256"}],"name":"deviceSyncStatus","outputs":[{"internalType":"enum ChainSyncStatus","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"globalLayerStatus","outputs":[{"internalType":"enum ChainSyncStatus","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"nftId","type":"uint256"}],"name":"isBorrowAllowed","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"nftId","type":"uint256"}],"name":"lastMirroredEpoch","outputs":[{"internalType":"uint32","name":"","type":"uint32"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"nftId","type":"uint256"}],"name":"lastSnapshotHash","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IYieldUpdateMirror.sol";
  readonly buildInfoId: "solc-0_8_19-1ef7364bee65fe47cce44adf0cd306f2b04bd606";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IYieldUpdateMirror"]: IYieldUpdateMirror$Type;
    ["contracts/interfaces/IYieldUpdateMirror.sol:IYieldUpdateMirror"]: IYieldUpdateMirror$Type;
  }
}