// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface BNBChainIds$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "BNBChainIds";
  readonly sourceName: "contracts/chain/BNBChainIds.sol";
  readonly abi: [];
  readonly bytecode: "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220869fee0f12fdfb8af903fcf7773dd3113d0063b7bf90995cde2b5815f8a0cbb564736f6c63430008130033";
  readonly deployedBytecode: "0x600080fdfea2646970667358221220869fee0f12fdfb8af903fcf7773dd3113d0063b7bf90995cde2b5815f8a0cbb564736f6c63430008130033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/chain/BNBChainIds.sol";
  readonly buildInfoId: "solc-0_8_19-1ef7364bee65fe47cce44adf0cd306f2b04bd606";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["BNBChainIds"]: BNBChainIds$Type;
    ["contracts/chain/BNBChainIds.sol:BNBChainIds"]: BNBChainIds$Type;
  }
}