// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ILendingPoolBnb$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ILendingPoolBnb";
  readonly sourceName: "contracts/interfaces/ILendingPoolBnb.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256[]","name":"nftIds","type":"uint256[]"},{"internalType":"uint256[]","name":"newCollaterals","type":"uint256[]"}],"name":"batchUpdateCollateralValueFromOracle","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"nftId","type":"uint256"}],"name":"getPosition","outputs":[{"internalType":"uint256","name":"debt","type":"uint256"},{"internalType":"uint256","name":"collateralValue","type":"uint256"},{"internalType":"uint256","name":"ltv","type":"uint256"},{"internalType":"uint256","name":"yieldPercentage","type":"uint256"},{"internalType":"address","name":"yieldToken","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"nftId","type":"uint256"},{"internalType":"uint256","name":"newCollateral","type":"uint256"}],"name":"updateCollateralValue","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ILendingPoolBnb.sol";
  readonly buildInfoId: "solc-0_8_19-1ef7364bee65fe47cce44adf0cd306f2b04bd606";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ILendingPoolBnb"]: ILendingPoolBnb$Type;
    ["contracts/interfaces/ILendingPoolBnb.sol:ILendingPoolBnb"]: ILendingPoolBnb$Type;
  }
}