// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IOracleRegistry$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IOracleRegistry";
  readonly sourceName: "contracts/interfaces/IOracleRegistry.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"provider","type":"address"}],"name":"isOracleProviderActive","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"minProvidersForConsensus","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"providerCount","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IOracleRegistry.sol";
  readonly buildInfoId: "solc-0_8_19-1ef7364bee65fe47cce44adf0cd306f2b04bd606";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IOracleRegistry"]: IOracleRegistry$Type;
    ["contracts/interfaces/IOracleRegistry.sol:IOracleRegistry"]: IOracleRegistry$Type;
  }
}