// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IProtocolParameterRegistry$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IProtocolParameterRegistry";
  readonly sourceName: "contracts/interfaces/IProtocolParameterRegistry.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"key","type":"bytes32"}],"name":"uintParam","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IProtocolParameterRegistry.sol";
  readonly buildInfoId: "solc-0_8_19-1ef7364bee65fe47cce44adf0cd306f2b04bd606";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IProtocolParameterRegistry"]: IProtocolParameterRegistry$Type;
    ["contracts/interfaces/IProtocolParameterRegistry.sol:IProtocolParameterRegistry"]: IProtocolParameterRegistry$Type;
  }
}