// ABIs matching the Solidity contracts in /contracts/

export const HardwareNFT_ABI = [
  "function registerDevice(bytes32 deviceId, uint8 deviceType, string greenfieldProofCID, bytes publicKey) external returns (uint256)",
  "function submitProof(uint256 tokenId, string newCID) external",
  "function submitProofWithContentHash(uint256 tokenId, string newCID, bytes32 contentHash) external",
  "function verifyDevice(uint256 tokenId) external",
  "function deactivateDevice(uint256 tokenId) external",
  "function approve(address to, uint256 tokenId) external",
  "function setApprovalForAll(address operator, bool approved) external",
  "function transferFrom(address from, address to, uint256 tokenId) external",
  "function setLendingPool(address _pool) external",
  "function setComplianceHook(address _hook) external",
  "function setClassRegistry(address registry) external",
  "function lendingPool() view returns (address)",
  "function complianceHook() view returns (address)",
  "function classRegistry() view returns (address)",
  "function isCollateralEligible(uint256 tokenId) view returns (bool)",
  "function canUseAsCollateral(uint256 tokenId) view returns (bool)",
  "function isProofFresh(uint256 tokenId) view returns (bool)",
  "function deviceClass(uint256 tokenId) view returns (uint8)",
  "function lastProofAt(uint256 tokenId) view returns (uint256)",
  "function yieldConfidenceTier(uint256 tokenId) view returns (uint8)",
  "function riskAdjustedCollateralWad(uint256 tokenId) view returns (uint256)",
  "function devices(uint256 tokenId) view returns (address owner, bytes32 deviceId, uint8 deviceType, uint256 registrationTime, uint256 lastProofTimestamp, bool isActive, string greenfieldProofCID, bytes publicKey, address hardwareBeneficialOwner, uint256 proofSequence, bytes32 lastProofContentHash, uint8 securityState, uint64 chainIdRegistered, uint8 yieldConfidence, uint8 collateralBinding, address collateralProtocol)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function balanceOf(address owner) view returns (uint256)",
  "function getOwnerDevices(address owner) view returns (uint256[])",
  "function PAUSER_ROLE() view returns (bytes32)",
  "function REGISTRAR_ROLE() view returns (bytes32)",
  "function DEVICE_GUARD_ROLE() view returns (bytes32)",
  "event DeviceRegistered(uint256 indexed tokenId, address indexed owner, bytes32 deviceId, uint8 deviceType, uint8 initialState)",
  "event ProofSubmitted(uint256 indexed tokenId, uint256 timestamp, string cid, bytes32 proofBinding, uint256 newSequence, bytes32 contentHash)",
  "event DeviceSecurityStateChanged(uint256 indexed tokenId, uint8 previous, uint8 next, address indexed by)",
  "event DeviceSpoofingSuspected(uint256 indexed tokenId, string reason, address indexed by)",
  "event DeviceFrozenForReview(uint256 indexed tokenId, address indexed by)",
];

export const LendingPool_ABI = [
  "function GOVERNOR_ROLE() view returns (bytes32)",
  "function PAUSER_ROLE() view returns (bytes32)",
  "function setGovernor(address _governor) external",
  "function setOracle(address _oracle) external",
  "function setMaxInitialLTV(uint256 bps) external",
  "function setOracleUpdatesPaused(bool paused) external",
  "function oracleUpdatesPaused() view returns (bool)",
  "function setFeeDiscountModule(address module) external",
  "function setComplianceHook(address _hook) external",
  "function setClassRegistry(address registry) external",
  "function setProtocolRiskMode(uint8 mode) external",
  "function setRestrictLiquidationToLiquidatorRole(bool restricted) external",
  "function setAllowLiquidationWithStaleCollateralRef(bool allowed) external",
  "function deposit(uint256 nftId, uint256 yieldPercentage, uint256 borrowAmount) external",
  "function repay(uint256 nftId) external",
  "function repayPartial(uint256 nftId, uint256 amount) external",
  "function liquidate(uint256 nftId) external",
  "function updateCollateralValue(uint256 nftId) external",
  "function updateCollateralValue(uint256 nftId, uint256 newCollateral) external",
  "function accrueInterest(uint256 nftId) external",
  "function pause() external",
  "function unpause() external",
  "function getPosition(uint256 nftId) view returns (uint256 debt, uint256 collateralValue, uint256 ltv, uint256 yieldPercentage, address yieldToken)",
  "function getPositionFull(uint256 nftId) view returns (uint256 debt, uint256 accruedInterest, uint256 collateralValue, uint256 ltv, address borrower, uint256 liquidationEligibleAt, uint64 lastCollateralRefAt)",
  "function getHealthFactorWad(uint256 nftId) view returns (uint256)",
  "function getHealthBand(uint256 nftId) view returns (uint8)",
  "function getPositionRiskSummary(uint256 nftId) view returns (uint256 totalOwed, uint256 hfWad, uint8 band, uint256 liqThresholdBps, uint256 ltvBps, bool collateralRefFresh)",
  "function maxAdditionalBorrow(uint256 nftId) view returns (uint256)",
  "function HEALTH_FACTOR_ONE() view returns (uint256)",
  "function minPostBorrowHealthFactorWad() view returns (uint256)",
  "function cautionHealthMinWad() view returns (uint256)",
  "function atRiskHealthMinWad() view returns (uint256)",
  "function repayPaused() view returns (bool)",
  "function positions(uint256 nftId) view returns (uint256 debt, uint256 collateralValue, uint256 ltv, uint256 yieldPercentage, address yieldToken, address borrower, uint256 lastUpdateTimestamp, uint256 accruedLpInterest, uint256 accruedProtocolInterest, uint256 liquidationEligibleAt, uint64 lastCollateralRefAt)",
  "function riskMode() view returns (uint8)",
  "function restrictLiquidationToLiquidatorRole() view returns (bool)",
  "function allowLiquidationWithStaleCollateralRef() view returns (bool)",
  "function liquidationThreshold() view returns (uint256)",
  "function maxInitialLTV() view returns (uint256)",
  "function stablecoin() view returns (address)",
  "function hardwareNFT() view returns (address)",
  "function complianceHook() view returns (address)",
  "function classRegistry() view returns (address)",
  "function LIQUIDATION_BONUS() view returns (uint256)",
  "function MAX_COLLATERAL_REF_STALE() view returns (uint256)",
  "event Deposited(address indexed borrower, uint256 indexed nftId, uint256 principal, uint256 originationFee, uint256 verificationFee, uint256 netToBorrower, uint256 yieldPercentage)",
  "event BorrowOpened(address indexed borrower, uint256 indexed nftId, uint256 principal, uint256 collateralValueWad, uint256 maxLtvBps, uint256 liquidationThresholdBps, uint256 healthFactorWad, uint8 healthBand, uint8 deviceClass, uint64 lastCollateralRefAt)",
  "event Repaid(address indexed borrower, uint256 indexed nftId, uint256 principalPaid, uint256 lpInterestPaid, uint256 protocolInterestPaid, uint256 remainingPrincipal, uint256 remainingAccruedInterest)",
  "event LoanRepayment(address indexed payer, uint256 indexed nftId, uint256 protocolInterestPaid, uint256 lpInterestPaid, uint256 principalPaid, uint256 remainingDebt, uint256 remainingAccruedInterest, bool fullClose)",
  "event HealthFactorUpdated(uint256 indexed nftId, uint256 hfWad, uint8 band, uint256 totalOwed, uint256 collateralWad)",
  "event PositionStateChanged(uint256 indexed nftId, uint8 band)",
  "event CollateralReleasedFromLoan(uint256 indexed nftId, address indexed borrower, bool fullClose)",
  "event Liquidated(address indexed liquidator, uint256 indexed nftId, uint256 amountRecovered, uint256 protocolLiquidationFee)",
  "event ProtocolRiskModeUpdated(uint8 indexed mode)",
  "event OracleUpdatesPausedUpdated(bool paused)",
  "event MaxInitialLTVUpdated(uint256 oldBps, uint256 newBps)",
  "event LiquidationWarning(uint256 indexed nftId, uint256 ltv, uint256 eligibleAt)",
];

/** Minimal ERC-20 for stablecoin approve / allowance (LendingPool repay & liquidate). */
export const ERC20_ABI = [
  "function approve(address spender, uint256 amount) external returns (bool)",
  "function allowance(address owner, address spender) view returns (uint256)",
];

export const YieldToken_ABI = [
  "function mint(address to, uint256 amount) external",
  "function burn(address from, uint256 amount) external",
  "function balanceOf(address) view returns (uint256)",
  "function totalSupply() view returns (uint256)",
  "function approve(address spender, uint256 amount) external returns (bool)",
  "function lendingPool() view returns (address)",
  "function hardwareNFT() view returns (address)",
  "function tokenizedPercentage() view returns (uint256)",
  "function underlyingRewardToken() view returns (address)",
];

export const YieldTokenFactory_ABI = [
  "function createYieldToken(address lendingPool, address hardwareNFT, uint256 nftId, uint256 yieldPercentage, address underlyingRewardToken) external returns (address)",
  "event YieldTokenCreated(address indexed token, address indexed lendingPool, uint256 nftId)",
];
