// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IRevenueRouter$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IRevenueRouter";
  readonly sourceName: "contracts/interfaces/IRevenueRouter.sol";
  readonly abi: [{"inputs":[{"internalType":"enum RevenueSource","name":"src","type":"uint8"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"routeFee","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IRevenueRouter.sol";
  readonly buildInfoId: "solc-0_8_19-1ef7364bee65fe47cce44adf0cd306f2b04bd606";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IRevenueRouter"]: IRevenueRouter$Type;
    ["contracts/interfaces/IRevenueRouter.sol:IRevenueRouter"]: IRevenueRouter$Type;
  }
}